config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :authors, only: [:new, :create, :show]
  resources :auths, only: [:new, :create, :destroy]
  resources :books, only: [:new, :create, :index]
  resources :libraries, only: [:new, :create, :index, :show]
  root :to => "auths#new" #, :id => '1'
  get 'store', :to => 'books#store'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates_uniqueness_of :name
  validates :name, presence: true, length: { minimum: 2, message: 'should have at least 2 characters.' }

  has_many :libraries, foreign_key: :author_id
  has_many :books, foreign_key: :author_id
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_libraries
  has_many :libraries, through: :book_libraries

  validates :name, presence: true, length: { minimum: 2, message: 'should have at least 2 characters.' }
  validate :greater_than_zero

  scope :desc, -> { order('created_at DESC') }

  def greater_than_zero
    errors.add(:amount, 'should be greater than 0') if amount.to_i < 1
  end
end

app/models/book_library.rb
class BookLibrary < ApplicationRecord
  belongs_to :book
  belongs_to :library
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :author
  has_many :book_libraries
  has_many :books, through: :book_libraries
  has_one_attached :image

  validates :name, presence: true, length: { minimum: 2, message: 'should have at least 2 characters.' }
  validate :logo_validation

  def logo_validation
    if image.attached?
      if image.blob.byte_size > 1_000_000
        image.purge
        errors[:base] << 'Too big'
      elsif !image.blob.content_type.starts_with?('image/')
        image.purge
        errors[:base] << 'Wrong format'
      end
    elsif !image.attached?
      errors.add(:image, 'should be added')
    end
  end

  scope :asc, -> { order('name ASC') }
end

app/controllers/application_controller.rb
# rubocop:disable Style/GuardClause
class ApplicationController < ActionController::Base
  helper_method :current_author
  helper_method :logged_in?

  def current_author
    Author.find_by(id: session[:author_id])
  end

  def logged_in?
    !current_author.nil?
  end

  def check_auth
    unless logged_in?
      flash[:alert] = 'Please sign in to access this page.'
      redirect_to new_auth_path
    end
  end
end
# rubocop:enable Style/GuardClause

app/controllers/authors_controller.rb
# rubocop:disable Style/GuardClause
class AuthorsController < ApplicationController
  before_action :check_auth, only: [:show]
  before_action :set_author, only: [:show]

  def show
    if current_author != set_author
      flash[:notice] = 'You are not allowed to view other authors\' profile.'
      redirect_to new_auth_path
    end
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        session[:author_id] = @author.id
        format.html { redirect_to new_auth_path, notice: 'Author account was successfully created.' }
      else
        format.html { redirect_to new_author_path, alert: @author.errors.full_messages.first }
      end
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  rescue StandardError
    @author = nil
  end

  def author_params
    params.require(:author).permit(:name)
  end
end
# rubocop:enable Style/GuardClause

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  include AuthsHelper
  def new
    redirect_to current_author if logged_in?
  end

  def create
    sign_in
  end

  def destroy
    session[:author_id] = nil
    respond_to do |format|
      format.html { redirect_to new_auth_path, notice: 'Successfully logged out.' }
    end
  end

  private

  def auth_params
    params.require(:auth).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :check_auth

  def index
    @books = current_author.books.desc.select { |book| book.libraries.exists? }
    @image = true
  end

  def store
    @books = current_author.books.desc.reject { |book| book.libraries.exists? }
    @image = false
  end

  def new
    @book = Book.new
    @libraries = current_author.libraries
    @message = if @libraries.size.zero?
                 'If you want to choose a category for your book, you should create a category before publishing it.'
               else
                 'Choose a category for you book.'
               end
  end

  def create
    @book = current_author.books.build(book_params)
    @library = Library.find_by(id: library_params[:library_id])

    @book.libraries << @library unless @library.nil?
    respond_to do |format|
      if @book.save
        format.html { redirect_to current_author, notice: 'Book was successfully created.' }
      else
        format.html { redirect_to new_book_path, alert: @book.errors.full_messages.first }
      end
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :amount)
  end

  def library_params
    params.require(:book).permit(:library_id)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[show edit update destroy]
  before_action :check_auth

  def index
    @libraries = current_author.libraries.order('name ASC')
  end

  def show
    if current_author.libraries.include? set_library
      @libray = set_library
      @books = set_library.books
      @book_author = true
    else
      flash[:notice] = 'You are not allowed to view other authors libraries.'
      redirect_to libraries_url
    end
  end

  def new
    @library = Library.new
  end

  def create
    @library = current_author.libraries.build(library_params)
    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Category was successfully created.' }
      else
        format.html { redirect_to new_library_path, alert: @library.errors.full_messages.first }
      end
    end
  end

  private

  def set_library
    @library = Library.find(params[:id])
  rescue StandardError
    @library = nil
  end

  def library_params
    params.require(:library).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
  def sign_in
    @author = Author.find_by(name: params[:name])

    if @author
      session[:author_id] = @author.id
      redirect_to @author
    else
      respond_to do |format|
        alert_text = 'Sorry, we have no author with this input. Please sign up, if you don\'t have an account.'
        format.html { redirect_to new_auth_path, alert: alert_text }
      end
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def icon(library)
    image_tag(library.image, class: 'iconic mr-3') if library
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/authors/new.html.erb
<div class="sign_form bg-custom-light rounded  p-2 py-5">
  <div class="shadow d-flex align-items-center justify-content-center custom-circle bg-custom text-white font-weight-bold text-center mb-5 p-5">
      <span class="h2">Create an Account</span>
  </div>
  <%= form_with(model: @author, local: true) do |form| %>
    <div class="actions">
      <%= form.text_field :name, placeholder: "Author name", class: "w-100 p-2" %><br>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="w-100 p-2 bg-success-custom my-5">
        <%= submit_tag("SIGN UP", :class=>"w-100 bg-success-custom text-white border-custom p-2") %><br>
      </div>
    </div>
  <% end %>
  <span>If you have an accout, then
    <%= link_to 'Sign in', new_auth_path %>
  <span>
</div>

app/views/authors/show.html.erb
<div class="sign_form bg-custom rounded text-center p-2 py-5 min-vh-100">
    <div class="shadow-lg d-flex align-items-center justify-content-center custom-circle bg-light text-custom font-weight-bold text-center mb-3">
       <%= gravatar_image_tag(current_author.name, alt: current_author.name, class:"img-responsive w-100 h-100 custom-circle")%>
    </div>
    <div class="text-light mb-5 h4">
      <%= current_author.name.downcase.capitalize %>
    </div>
    <p class="notice text-white"><%= notice %></p>
    
    <div class="text-light mb-3 h4 text-left p-0 px-3 d-flex">
      <div class="svg_holder mr-3 h1">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-book" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M3.214 1.072C4.813.752 6.916.71 8.354 2.146A.5.5 0 0 1 8.5 2.5v11a.5.5 0 0 1-.854.354c-.843-.844-2.115-1.059-3.47-.92-1.344.14-2.66.617-3.452 1.013A.5.5 0 0 1 0 13.5v-11a.5.5 0 0 1 .276-.447L.5 2.5l-.224-.447.002-.001.004-.002.013-.006a5.017 5.017 0 0 1 .22-.103 12.958 12.958 0 0 1 2.7-.869zM1 2.82v9.908c.846-.343 1.944-.672 3.074-.788 1.143-.118 2.387-.023 3.426.56V2.718c-1.063-.929-2.631-.956-4.09-.664A11.958 11.958 0 0 0 1 2.82z"/>
          <path fill-rule="evenodd" d="M12.786 1.072C11.188.752 9.084.71 7.646 2.146A.5.5 0 0 0 7.5 2.5v11a.5.5 0 0 0 .854.354c.843-.844 2.115-1.059 3.47-.92 1.344.14 2.66.617 3.452 1.013A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.276-.447L15.5 2.5l.224-.447-.002-.001-.004-.002-.013-.006-.047-.023a12.582 12.582 0 0 0-.799-.34 12.96 12.96 0 0 0-2.073-.609zM15 2.82v9.908c-.846-.343-1.944-.672-3.074-.788-1.143-.118-2.387-.023-3.426.56V2.718c1.063-.929 2.631-.956 4.09-.664A11.956 11.956 0 0 1 15 2.82z"/>
        </svg>
      </div>
      <div class="link_holder">
        <%= link_to 'Categorized Books', books_path, class: "text-light h5" %>
      </div>
    </div>
    
    <div class="text-light mb-3 h4 text-left p-0 px-3 d-flex">
      <div class="svg_holder mr-3 h1">
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-shop" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M0 15.5a.5.5 0 0 1 .5-.5h15a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5zM3.12 1.175A.5.5 0 0 1 3.5 1h9a.5.5 0 0 1 .38.175l2.759 3.219A1.5 1.5 0 0 1 16 5.37v.13h-1v-.13a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.13H0v-.13a1.5 1.5 0 0 1 .361-.976l2.76-3.22z"/>
        <path d="M2.375 6.875c.76 0 1.375-.616 1.375-1.375h1a1.375 1.375 0 0 0 2.75 0h1a1.375 1.375 0 0 0 2.75 0h1a1.375 1.375 0 1 0 2.75 0h1a2.375 2.375 0 0 1-4.25 1.458 2.371 2.371 0 0 1-1.875.917A2.37 2.37 0 0 1 8 6.958a2.37 2.37 0 0 1-1.875.917 2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.5h1c0 .76.616 1.375 1.375 1.375z"/>
        <path d="M4.75 5.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm3.75 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm3.75 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
        <path fill-rule="evenodd" d="M2 7.846V7H1v.437c.291.207.632.35 1 .409zm-1 .737c.311.14.647.232 1 .271V15H1V8.583zm13 .271a3.354 3.354 0 0 0 1-.27V15h-1V8.854zm1-1.417c-.291.207-.632.35-1 .409V7h1v.437zM3 9.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5V15H7v-5H4v5H3V9.5zm6 0a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-4zm1 .5v3h2v-3h-2z"/>
      </svg>
      </div>
      <div class="link_holder">
      <%= link_to 'Uncategorized Books', store_path, class: "text-light h5" %>
      </div>
      </div>
    
    <div class="text-light mb-5 h4 text-left p-0 px-3 d-flex">
      <div class="svg_holder mr-3 h1">
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-collection" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14.5 13.5h-13A.5.5 0 0 1 1 13V6a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5zm-13 1A1.5 1.5 0 0 1 0 13V6a1.5 1.5 0 0 1 1.5-1.5h13A1.5 1.5 0 0 1 16 6v7a1.5 1.5 0 0 1-1.5 1.5h-13zM2 3a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11A.5.5 0 0 0 2 3zm2-2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7A.5.5 0 0 0 4 1z"/>
      </svg>
      </div>
      <div class="link_holder">
      <%= link_to 'My Library', libraries_path, class: "text-light h5" %>
    </div>
    </div>
    
    <div class="text-light mb-3 h4 text-left p-0 px-3 d-flex">
      <div class="svg_holder mr-3 h1">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-door-open" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M1 15.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5zM11.5 2H11V1h.5A1.5 1.5 0 0 1 13 2.5V15h-1V2.5a.5.5 0 0 0-.5-.5z"/>
          <path fill-rule="evenodd" d="M10.828.122A.5.5 0 0 1 11 .5V15h-1V1.077l-6 .857V15H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117z"/>
          <path d="M8 9c0 .552.224 1 .5 1s.5-.448.5-1-.224-1-.5-1-.5.448-.5 1z"/>
        </svg>
      </div>
      <div class="link_holder">
      <%= link_to 'Log Out', auth_path, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "text-light h5" %><br>
    </div>
    </div>
  </div>

app/views/auths/new.html.erb
<div class="sign_form bg-custom-light rounded p-2 py-5">
  <div class="shadow d-flex align-items-center justify-content-center custom-circle bg-custom text-white font-weight-bold text-center mb-5 p-5">
      <span class="h2">Sign In</span>
  </div>
  <%= form_with(model: @auth, local: true, url: "/auths") do |form| %>
    <div class="actions">
      <%= form.text_field :name, placeholder: "Author name", class: "w-100 p-2" %><br>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="w-100 p-2 bg-success-custom my-5">
        <%= submit_tag("SIGN IN", :class=>"w-100 bg-success-custom text-white border-custom p-2") %><br>
      </div>
    </div>
  <% end %>
  <span>If you don't have an accout, then
    <%= link_to 'Sign up', new_author_path %>
  <span>
</div>

app/views/books/_form.html.erb
<div class="sign_form bg-custom-light rounded  p-2 py-5">
  
  <%= form_with(model: book, local: true) do |form| %>
    <div class="actions">
      <%= form.text_field :name, placeholder: "Name", class: "w-100 p-2 my-2" %><br>
      <%= form.number_field :amount, placeholder: "Price", class: "w-100 p-2 my-2" %><br>
      
      <%= form.label :library_id, @message , class: "w-100 m-0 mt-2 p-0" %>
      <%= form.select :library_id, options_from_collection_for_select(@libraries, :id, :name), {:include_blank => 'None'}, {:class => 'w-100 p-2 my-2'} %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="w-100 p-2 bg-success-custom my-5">
        <%= submit_tag("Publish", :class=>"w-100 bg-success-custom text-white border-custom p-2") %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/_list.html.erb
<div class=" m-0 p-3 bg-white d-flex justify-content-between h4"><span class="text-secondary">Total:</span> <span class="font-weight-bold"> <%= @books.sum{|book| book.amount} %> &#36; </span></div>
<div class=" m-0 p-3  bg-light-gray">
  <p id="notice m-0 p-0"><%= notice %></p>
  <% @books.each do |book| %>
    <div class="my-2 bg-white p-3 d-flex justify-content-start">
    <% library=current_author.libraries.select{|l| book.libraries.include?(l)}.first %>
    <%= icon(library) %>
      <div>
        <p class="text-secondary h6 m-0 p-0 pt-2"><strong>Book Name: </strong><%= book.name %></p>
        <% unless @book_author.nil? %>
          <p class="text-secondary h6 m-0 p-0 pt-2 h6"><strong>Author: </strong><%= book.author.name %></p>
        <% end %>
        <p class="text-secondary h6 m-0 p-0 pt-3"><strong>Published: </strong> <%= book.created_at.day %>-<%= book.created_at.month %>-<%= book.created_at.year %></p>
      </div>
      <div class="ml-auto">
        <p class="text-secondary h6 m-0 p-0 pt-2 font-weight-bold"><%= book.amount %> &#36; </p>
      </div>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<% @title="Categorized" %>
<%= render 'layouts/navbar' %>
<%= render 'list' %>
<div class="w-100 p-2 bg-success-custom m-0" >
    <%= link_to 'PUBLISH NEW', new_book_path, :class=>"d-block w-100 bg-success-custom text-white border-custom p-2 text-center" %>
</div>

app/views/books/new.html.erb
<% @title="New Book" %>
<%= render 'layouts/navbar' %>
<%= render 'form', book: @book %>

app/views/books/store.html.erb
<% @title="Uncategorized" %>
<%= render 'layouts/navbar' %>
<%= render 'list' %>
<div class="w-100 p-2 bg-success-custom m-0" >
    <%= link_to 'PUBLISH NEW', new_book_path, :class=>"d-block w-100 bg-success-custom text-white border-custom p-2 text-center" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="shadow navbar navbar-dark bg-nav">
  <%= link_to :back, class: "navbar-brand text-custom" do %>
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
      <path fill-rule="evenodd" d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z"/>
      <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z"/>
    </svg>
  <% end %>
  <div class="h3 text-light p-0 m-0 mx-5"> <%= @title.truncate(23) %> </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to 'Profile', current_author, class: "nav-item nav-link active" %>
      <%= link_to 'Categorized', books_path, class: "nav-item nav-link" %>
      <%= link_to 'Uncategorized', store_path, class: "nav-item nav-link" %>
      <%= link_to 'My Library', libraries_path, class: "nav-item nav-link" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <div class="container-fluid container-100vh p-0">
      <div class="row w-100  align-items-center justify-content-center p-0">
        <div class="col-12 col-sm-9 col-md-7 col-lg-5 p-0 border-custom-2">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/libraries/_list.html.erb
<div class="shadow m-0 p-3  bg-light-gray">
  <p id="notice m-0 p-0"><%= notice %></p>
  <% @libraries.each do |library| %>
    <%= link_to(library) do %>
      <div class="my-2 bg-white p-3 d-flex justify-content-start">
        <%= image_tag(library.image, class: "iconic mr-3") %>
        <div> 
          <p class="text-secondary h6 m-0 p-0 py-1"><strong>Category Name: </strong><%= library.name %></p>
          <p class="text-secondary h6 m-0 p-0 py-2"><strong>Created: </strong> <%= library.created_at.day %>-<%= library.created_at.month %>-<%= library.created_at.year %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/libraries/index.html.erb
<% @title="My Library" %>
<%= render 'layouts/navbar' %>
<%= render 'list' %>
<div class="w-100 p-2 bg-success-custom m-0">
    <%= link_to 'CREATE A NEW CATEGORY', new_library_path, :class=>"d-block w-100 bg-success-custom text-white border-custom p-2 text-center" %>
</div>

app/views/libraries/new.html.erb
<% @title="New Category" %>
<%= render 'layouts/navbar' %>
<div class="sign_form bg-custom-light rounded  p-2 py-5">
  
  <%= form_with(model: @library, local: true) do |form| %>
    <div class="actions">
      <%= form.text_field :name, placeholder: "Category Name", class: "w-100 p-2" %><br>
      <%= form.file_field :image, placeholder: "Category Icon", class: "w-100 p-2 border mt-3" %><br>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="w-100 p-2 bg-success-custom my-5">
        <%= submit_tag("CREATE", :class=>"w-100 bg-success-custom text-white border-custom p-2") %><br>
      </div>
    </div>
  <% end %>
</div>

app/views/libraries/show.html.erb
<% @title=@library.name %>
<%= render 'layouts/navbar' %>
<%= render 'books/list' %>